uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_003

Gemfile
Gemfile.lock
README.md
config/database.yml
log/development.log

Had to edit gemfile and production db to start heroku site. Readme includes heroku link.

Heroku creation

---

app/assets/javascripts/grid.js
app/controllers/pages_controller.rb
app/models/game_user.rb
app/views/pages/grid.html.erb
config/routes.rb
db/migrate/20241126234149_add_position_to_game_users.rb
db/migrate/20241127034623_add_defaults_to_game_users.rb
db/schema.rb
spec/factories/game_users.rb
spec/factories/games.rb
spec/models/game_user_spec.rb

New feature ✨ Player Movement

---

app/assets/stylesheets/ai_generated_skins.scss
app/assets/stylesheets/chats.scss
app/assets/stylesheets/home.scss
app/assets/stylesheets/registration.scss
app/assets/stylesheets/user.scss
app/views/ai_generated_skins/new.html.erb
app/views/chats/show.html.erb
app/views/user/index.html.erb

Fixing some styling on pages like the AI sprite generation, account page, create account page and chat page

Code refactor ♻️ Fixing styling and format for some pages

---

app/views/interactions/show.html.erb

Bug fix 🐛 turning off attack buttons when fight is over

---

app/views/pages/grid.html.erb
app/views/store/index.html.haml
log/development.log

Added items to shop and fixed grid gif loading issue

---

.github/workflows/rspec-tests.yml
Gemfile.lock

Added GitHub Actions workflow for running RSpec tests

---

db/migrate/20241119081613_add_reset_password_fields_to_users.rb

change for rake db:migrate

---

app/controllers/ai_generated_skins_controller.rb

added environment variable for openai api key

---

app/controllers/store_controller.rb

- This was an easy button redirect fix, no tests were fixed, no issue closed

Fixed button to generate ai avatar

---

config/environments/production.rb

added amazon as active storage service

---

app/controllers/ai_generated_skins_controller.rb

Fixing prompt to for ai gen to be more mystical

---

app/controllers/user_controller.rb
app/views/user/index.html.erb
config/environments/development.rb
config/routes.rb

users can now upload a new photo to change their profile photo
needs css styling for the buttons

enabled users to edit profile pic in account page

---

app/controllers/interactions_controller.rb

Added shard reward for passing levels

---

app/controllers/store_controller.rb

checks if user has credit card saved to account before buying shards

credit card check fix

---

app/controllers/interactions_controller.rb
app/views/user/index.html.erb

added back buttons that were deleted for adding friends and chatting

---

config/cable.yml

changing redis for prod

---

config/cable.yml
config/initializers/redis.rb

added initializer file and tls to cable

---

config/initializers/redis.rb

edit to redis intializer

---

spec/views/chats/show.html.erb_spec.rb
spec/views/credit_cards/edit.html.erb_spec.rb
spec/views/credit_cards/new.html.erb_spec.rb
spec/views/credit_cards/show.html.erb_spec.rb
spec/views/games/index.html.erb_spec.rb
spec/views/pages/grid.html.erb_spec.rb

View Testing

---

config/cable.yml

changed tls for ssl because it wasn't recognized

---

config/cable.yml

formatting fix

---

Gemfile
Gemfile.lock
config/cable.yml
config/environments/production.rb

redis change

---

Gemfile
Gemfile.lock

gemfile issue with redis rails

---

spec/controllers/arena_controller_spec.rb
spec/controllers/games_controller_spec.rb
spec/controllers/interactions_controller_spec.rb
spec/controllers/pages_controller_spec.rb
spec/controllers/user_controller.rb
spec/spec_helper.rb

Further controller testing

---

Gemfile

fix gemfile

---

spec/models/friendship_spec.rb
spec/models/game_spec.rb
spec/models/game_user_spec.rb
spec/models/message_spec.rb
spec/models/skin_spec.rb
spec/models/user_spec.rb
spec/models/weapon_spec.rb
spec/spec_helper.rb

Updated tests

---

spec/factories/skins.rb
spec/rails_helper.rb
spec/spec_helper.rb
spec/views/ai_generated_skins/new.html.erb_spec.rb
spec/views/interactions/show.html.erb_spec.rb
spec/views/inventory/index.html.erb_spec.rb
spec/views/store/index.html.haml_spec.rb

Attempted to fix tests

---

spec/views/password_resets/create.html.erb_spec.rb
spec/views/password_resets/edit.html.erb_spec.rb
spec/views/password_resets/new.html.erb_spec.rb
spec/views/registrations/new.html.erb_spec.rb
spec/views/selections/index.html.erb_spec.rb
spec/views/sessions/new.html.erb_spec.rb
spec/views/user/index.html.erb_spec.rb

Further view testing

---

app/views/arena/index.html.erb
app/views/interactions/show.html.erb

fixed useWeapon error
